<?php
$value = array (
  'twitter' => 'https://www.vipcomsistemas.com.br',
  'facebook' => 'https://www.facebook.com/vipcomsis',
  'instagram' => 'https://www.instagram.com/vipcomsistemasweb/',
  'youtube' => 'https://www.youtube.com/@vipcomsistemas8291?app=desktop',
  'colormenusuperior' => '#094281',
  'colormenusuperiorhover' => '#094281',
  'colormenusuperiorborder' => '#224774',
  'background_titulo_destaque' => '#303030',
  'botaodetalhe' => '#222222',
  'botaodetalhehover' => '#303030',
  'colortitulocidade' => '#0f0f0f',
  'coloremailofertas' => '#000000',
  'colorfundocidades' => '#336105',
  'colortextoh3' => '#a1e042',
  'color_destaque_titulo' => '#244973',
  'color_destaque_titulo_txt' => '#FFF',
  'color_destaque_botao' => '#CACFDC',
  'color_detalhe_oferta_home' => '#E7E9EF',
  'color_detalhe_oferta_home_txt' => '#303030',
  'oferta_valor' => '#000',
  'color_qtd_vendido' => '#FF7300',
  'color_contadornovo' => '#80B300',
  'color_fundo_meio_rodape' => '#03254B',
  'cor_letra_topo' => '#fff',
  'rodapedetalhe' => '#F2F2F2',
  'color_fundo_laterais_rodape' => '#f1f6f9',
  'background_titulos' => '#F1F1F1',
  'background_oferta_nacional' => '#B33191',
  'fundooferta' => '#fff',
  'topodetalhe' => 'url(/skin/padrao/background/body-bg11.png)',
  'bgheader' => '',
  'btn-add' => '',
  'subtitle' => '',
  'cormapa' => '',
  'fill' => '',
  'not-found' => '',
  'list-city-offer' => '',
  'price-list-offer' => '',
  'price-box' => '',
  'info-block' => '',
  'welcome' => '',
  'txtrodape' => '',
  'rodape' => '',
);
?>